<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);TUnitAssertions0002</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="TUnit.Assertions.Should" />
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ServiceLib\ServiceLib.csproj" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
